name: trendency
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

targets:
  $default:
    builders:
      json_serializable:
        options:
          # Options configure how source code is generated for every
          # `@JsonSerializable`-annotated class in the package.
          #
          # The default value for each is listed.
          any_map: false
          checked: false
          constructor: ""
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: false
          field_rename: none
          generic_argument_factories: false
          ignore_unannotated: true
          include_if_null: true

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  provider: ^6.0.2
  url_launcher: ^6.0.20
  google_fonts: ^2.3.1
  infinite_scroll_pagination: ^3.1.0
  bottom_navy_bar: ^6.0.0
  image_picker: ^0.8.4+11
  webview_flutter: ^3.0.1
  dio_cookie_manager: ^2.0.0
  video_player: ^2.3.0
  flutter_secure_storage: ^5.0.2
  flutter_spinkit: ^5.1.0
  chewie: ^1.3.2
  shimmer: ^2.0.0
  camera: ^0.9.4+18
  photo_view: ^0.13.0
  flutter_native_splash: ^2.1.2+1
  lottie: ^1.2.2
  routemaster: ^0.10.0-dev5
  font_awesome_flutter: ^9.0.0
  page_transition: ^2.0.5
  http_interceptor: ^1.0.2
  http: ^0.13.4
  carousel_slider: ^4.0.0
  flutter_signin_button: ^2.0.0
  bottom_drawer: ^0.0.5
  flutter_inappwebview: ^5.3.2
  flutter_dotenv: ^5.0.2
  get: ^4.6.1
  jwt_decode: ^0.3.1
  dio: ^4.0.6
  cached_network_image: ^3.2.0
  flutter_svg: ^1.0.3
  expandable_text: ^2.3.0
  intl: ^0.17.0
  extended_text_field: ^10.0.1

dev_dependencies:
  json_serializable: ^6.1.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.8

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/lottie/
    - .env
    - assets/fonts/
    - assets/svgs/
    - assets/lottie/trendency_hashtag.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
